### ISSUE TITLE
Include in official TikZ distribution

### ISSUE THREAD

**Issue by opieters** [Qrrbrbirlbel/TikZ-misc#1]
It would be useful if these libraries were included in the official TikZ distribution and documentation, since installing and using them is not very convenient. 

I know it is possible using [this technique](https://tex.stackexchange.com/questions/187193/how-to-install-tikz-pgf-libraries), but this is not very convenient.

**Comment by hmenke** [comment]
It is not possible to include these libraries in the official TikZ distribution because they lack the appropriate license.  To qualify for inclusion they would have to be dual-licensed under GPLv2 + LPPLv1.3c

**Comment by Qrrbrbirlbel** [comment]
@hmenke Can you point me in the right direction how I would accomplish this?

When I create a new `LICENSE` file in my repository GitHub has a button to choose a license template—but how would I do this with two licenses?

Or should I try to directly commit to the official [repository](https://github.com/pgf-tikz/pgf)? (And how would I approach this?)

The most interesting library will be `paths.ortho` because it interferes on the back-end of the TikZ engine and it might not use the standard naming scheme (for macros or for keys).

**Comment by hmenke** [comment]
@Qrrbrbirlbel Thanks for picking this up!

Please drop these two files into your repository (in a subdirectory if you wish)

- https://github.com/pgf-tikz/pgf/raw/master/doc/generic/pgf/licenses/gnu-public-license-2.txt
- https://github.com/pgf-tikz/pgf/raw/master/doc/generic/pgf/licenses/latex-project-public-license-1.3c.txt

and add a file called `LICENSE` with contents similar to this:

```
The code of this package is dual-license. This means that
you can decide which license you wish to use when using the
package. The two options are:

a) You can use the GNU Public License, version 2.
b) You can use the LaTeX Project Public License, version 1.3c.
```

**Comment by Qrrbrbirlbel** [comment]
@hmenke I've done that.

**Comment by Qrrbrbirlbel** [comment]
@opieters I've added the needed licenses.

Whether the PGF/TikZ team implements any of these libraries is outside of my purview.
